import React, { useCallback, useEffect, useState } from 'react';
import {
    Edit,
    SimpleForm,
    TextInput,
    BooleanInput,
    required,
    SaveButton,
    Toolbar,
    ListButton,
    TopToolbar,
} from 'react-admin';
import { Editor } from '@tinymce/tinymce-react';
import { useFormContext } from 'react-hook-form';
import { Card, Box, Typography } from '@mui/material';
import { transliterate } from '../../utils/transliterate';

interface ContentInputProps {
    source: string;
    label: string;
}

const ContentInput = ({ source, label }: ContentInputProps) => {
    const { setValue, watch } = useFormContext();
    const content = watch(source);

    const extractTempImages = (htmlContent: string): string[] => {
        const parser = new DOMParser();
        const doc = parser.parseFromString(htmlContent, 'text/html');
        const images = doc.querySelectorAll('img');
        const tempImageUrls: string[] = [];

        images.forEach((img) => {
            const src = img.getAttribute('src');
            if (src && src.includes('/uploads/news/temp/') && !tempImageUrls.includes(src)) {
                tempImageUrls.push(src);
            }
        });

        return tempImageUrls;
    };

    const handleEditorChange = useCallback(
        (newContent: string) => {
            setValue(source, newContent, { shouldValidate: true });
            const tempUrls = extractTempImages(newContent);
            // Временные изображения сохраняются в контексте для возможного использования
            setValue('tempImages', tempUrls);
        },
        [setValue, source]
    );

    return (
        <Box sx={{ mb: 2 }}>
            <Typography variant="body2" sx={{ mb: 1, fontWeight: 'medium' }}>
                {label}
            </Typography>
            <Editor
                tinymceScriptSrc="/tinymce/tinymce.min.js"
                value={content || ''}
                onEditorChange={handleEditorChange}
                init={{
                    height: 500,
                    menubar: true,
                    plugins: [
                        'advlist',
                        'autolink',
                        'lists',
                        'link',
                        'image',
                        'charmap',
                        'anchor',
                        'searchreplace',
                        'visualblocks',
                        'code',
                        'fullscreen',
                        'insertdatetime',
                        'media',
                        'table',
                        'help',
                        'wordcount',
                    ],
                    toolbar:
                        'undo redo | formatselect | bold italic underline strikethrough | ' +
                        'alignleft aligncenter alignright alignjustify | ' +
                        'bullist numlist outdent indent | link image | ' +
                        'removeformat | code | help',
                    base_url: '/tinymce',
                    suffix: '.min',
                    image_uploadtab: true,
                    images_upload_url: `${import.meta.env.VITE_API_URL}/api/posts/upload-image?entity=news`,
                    images_upload_base_path: `${import.meta.env.VITE_API_URL}`,
                    automatic_uploads: true,
                    file_picker_types: 'image',
                    content_style: 'body { font-family:Helvetica,Arial,sans-serif; font-size:14px }',
                }}
            />
        </Box>
    );
};

interface SlugInputProps {
    source: string;
    label: string;
    fullWidth?: boolean;
}

const SlugInput = ({ source, label, ...props }: SlugInputProps) => {
    const { setValue, watch } = useFormContext();
    const title = watch('title');
    const slug = watch(source);
    const [initialSlug] = useState(slug);
    const [isSlugManuallyEdited, setIsSlugManuallyEdited] = useState(false);

    useEffect(() => {
        // При первой загрузке проверяем, отличается ли текущий slug от автогенерированного
        if (initialSlug && title) {
            const autoGeneratedSlug = transliterate(title);
            if (initialSlug !== autoGeneratedSlug) {
                setIsSlugManuallyEdited(true);
            }
        }
    }, [initialSlug, title]);

    useEffect(() => {
        // Автогенерация slug только если он пустой или не был отредактирован вручную
        if (title && !isSlugManuallyEdited && (!slug || slug === '')) {
            const generatedSlug = transliterate(title);
            setValue(source, generatedSlug);
        }
    }, [title, slug, setValue, source, isSlugManuallyEdited]);

    const handleSlugChange = (value: string) => {
        setIsSlugManuallyEdited(true);
        setValue(source, value);
    };

    return (
        <TextInput
            source={source}
            label={label}
            helperText="Изменение slug может нарушить существующие ссылки"
            onChange={handleSlugChange}
            validate={required()}
            {...props}
        />
    );
};

const NewsEditActions = () => (
    <TopToolbar>
        <ListButton />
    </TopToolbar>
);

const NewsEditToolbar = () => (
    <Toolbar>
        <SaveButton />
    </Toolbar>
);

export const NewsEdit = () => (
    <Edit title="Редактирование новости" actions={<NewsEditActions />}>
        <Card className="p-6">
            <SimpleForm toolbar={<NewsEditToolbar />}>
                <TextInput
                    source="title"
                    label="Заголовок"
                    validate={required()}
                    fullWidth
                />

                <TextInput
                    source="shortDescription"
                    label="Краткое описание"
                    validate={required()}
                    multiline
                    rows={3}
                    fullWidth
                />

                <ContentInput
                    source="content"
                    label="Основное содержание"
                />

                <SlugInput
                    source="slug"
                    label="Slug"
                    fullWidth
                />

                <BooleanInput
                    source="isPublished"
                    label="Опубликовать"
                />

                <TextInput
                    source="metaTitle"
                    label="Meta Title"
                    fullWidth
                />

                <TextInput
                    source="metaDescription"
                    label="Meta Description"
                    multiline
                    rows={3}
                    fullWidth
                />
            </SimpleForm>
        </Card>
    </Edit>
); 